#!/usr/bin/env python3
"""Move the abandoned reconstructions somewhere they will survive a scratchpad wipe.

72 still-unmatched functions (72,680 bytes) have a live reconstruction sitting in the session
scratchpad. That directory is temporary and the project has already lost match snapshots to a
wipe once. This copies the best snapshot per function into tools/nearmiss/ under a predictable
name so any future session can find them, and scans for secrets first -- these files were
written by many past agent sessions and are about to enter git history, which is not something
you can quietly undo.
"""
import os, re, json, shutil, sys

REPO = "/mnt/c/Users/ssyla/OneDrive/Desktop/conker/conker decomp"
S = os.path.dirname(os.path.abspath(__file__))
DEST = os.path.join(REPO, "tools", "nearmiss")

rows = json.load(open(os.path.join(S, "backlog.json")))

SECRET = re.compile(
    r'ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}|sk-ant-[A-Za-z0-9_\-]{20,}'
    r'|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----'
    r'|(?i:api[_-]?key|secret|passwd|password)\s*[:=]\s*["\'][^"\']{8,}["\']')

flagged, exported = [], []
for r in rows:
    src = os.path.join(S, r["file"])
    if not os.path.exists(src):
        continue
    txt = open(src, errors="replace").read()
    hits = SECRET.findall(txt)
    if hits:
        flagged.append((r["file"], hits[:3]))
        continue
    exported.append(r)

if flagged:
    print("SECRETS FOUND -- these files were NOT exported:")
    for f, h in flagged:
        print(f"  {f}: {h}")
    print()

if "--dry-run" in sys.argv:
    print(f"would export {len(exported)} files to {DEST}")
    sys.exit(0)

os.makedirs(DEST, exist_ok=True)
for r in exported:
    shutil.copyfile(os.path.join(S, r["file"]), os.path.join(DEST, r["func"] + ".c"))

rows_sorted = sorted(exported, key=lambda r: -r["bytes"])
with open(os.path.join(DEST, "backlog.tsv"), "w") as fh:
    fh.write("func\tbytes\ttu\torigin_snapshot\tfilename_hint\n")
    for r in rows_sorted:
        fh.write(f"{r['func']}\t{r['bytes']}\t{r['tu']}\t{r['file']}\t{r['score_hint'] or '-'}\n")

tot = sum(r["bytes"] for r in exported)
open(os.path.join(DEST, "README.md"), "w").write(f"""# Abandoned reconstructions

{len(exported)} functions, **{tot:,} bytes**, that are still `#pragma GLOBAL_ASM` stubs but
already have a C reconstruction someone wrote and then dropped when the score plateaued.
Recovered from a session scratchpad (a temporary directory) so they stop being one wipe away
from gone.

One file per function, named `<func>.c`. `backlog.tsv` carries the size, owning TU, and the
original snapshot filename.

## Read this before using one

**These are UNVERIFIED.** Specifically:

* **The scores are unknown.** `filename_hint` is parsed out of the original filename and is a
  guess, not a measurement. Some are real scores, some were TU load addresses. Run
  `tools/rescore_backlog.sh` to replace them with measured numbers -- that is the step that
  turns this directory from a pile into a work queue.
* **They may not compile.** They were written against headers that have drifted since.
* **They may contain fake-match constructs.** Some pre-date the no-fake policy. Audit every
  one against the banned list in `tools/ido_cookbook.md` -- `new_var`, `dummy_label`,
  volatile-to-pin, `if (0) {{}}`, self-assignment, `x && x`, no-op mask chains, empty
  do-while, `&local`-to-force-a-reload -- **before** shipping anything derived from them.
  A score of 0 is necessary, not sufficient.
* **A definition here does not mean the function is close.** It means somebody started.

## Why they are worth keeping

Structure is the expensive half of a match and registers are the cheap half (see the
register-colouring section of `tools/ido_cookbook.md`). Each of these files is structural work
already paid for. Re-scored and sorted, the low end of this list is the cheapest remaining
byte source in the project.

Generated by `tools/backlog.py`.
""")

print(f"exported {len(exported)} reconstructions ({tot:,} bytes) -> tools/nearmiss/")
print(f"skipped {len(flagged)} for secrets")
